<a href="https://colab.research.google.com/github/platoml/869_course/blob/main/event3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML Cup Event #3

In [1]:
import pandas as pd
import numpy as np

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import sklearn
print('The scikit-learn version is {}.'.format(sklearn.__version__))

The scikit-learn version is 0.22.2.post1.


In [3]:
import os
os.getcwd()

'/content'

In [5]:
df = pd.read_csv("diabetes_train.csv")

Id_col = 'Id'
target_col = 'diabetes'
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576 entries, 0 to 575
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Id                  576 non-null    int64  
 1   num_times_pregnant  576 non-null    int64  
 2   plasma_glucose      576 non-null    int64  
 3   DBP                 576 non-null    int64  
 4   triceps_skin        576 non-null    int64  
 5   serum_insulin       576 non-null    int64  
 6   BMI                 576 non-null    float64
 7   pedigree            576 non-null    float64
 8   age                 576 non-null    int64  
 9   diabetes            576 non-null    int64  
dtypes: float64(2), int64(8)
memory usage: 45.1 KB


Id  num_times_pregnant  plasma_glucose  DBP  ...   BMI  pedigree  age  diabetes
0  358                  13             129    0  ...  39.9     0.569   44         1
1   74                   4             129   86  ...  35.1     0.231   23         0
2  353                   3              61   82  ...  34.4     0.243   46         0
3  498                   2              81   72  ...  30.1     0.547   25         0
4  146                   0             102   75  ...   0.0     0.572   21         0

[5 rows x 10 columns]

In [6]:
from sklearn.model_selection import train_test_split

X = df.drop([Id_col, target_col], axis=1)
y = df[target_col]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
X.info()
X.shape
X.head()

X_train.info()
X_train.shape
X_train.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576 entries, 0 to 575
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   num_times_pregnant  576 non-null    int64  
 1   plasma_glucose      576 non-null    int64  
 2   DBP                 576 non-null    int64  
 3   triceps_skin        576 non-null    int64  
 4   serum_insulin       576 non-null    int64  
 5   BMI                 576 non-null    float64
 6   pedigree            576 non-null    float64
 7   age                 576 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 36.1 KB


(576, 8)

num_times_pregnant  plasma_glucose  DBP  ...   BMI  pedigree  age
0                  13             129    0  ...  39.9     0.569   44
1                   4             129   86  ...  35.1     0.231   23
2                   3              61   82  ...  34.4     0.243   46
3                   2              81   72  ...  30.1     0.547   25
4                   0             102   75  ...   0.0     0.572   21

[5 rows x 8 columns]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 460 entries, 437 to 102
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   num_times_pregnant  460 non-null    int64  
 1   plasma_glucose      460 non-null    int64  
 2   DBP                 460 non-null    int64  
 3   triceps_skin        460 non-null    int64  
 4   serum_insulin       460 non-null    int64  
 5   BMI                 460 non-null    float64
 6   pedigree            460 non-null    float64
 7   age                 460 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 32.3 KB


(460, 8)

num_times_pregnant  plasma_glucose  DBP  ...   BMI  pedigree  age
437                   6             102   82  ...  30.8     0.180   36
63                    7             142   60  ...  28.8     0.687   61
208                   1             119   44  ...  35.5     0.280   25
60                    8             143   66  ...  34.9     0.129   41
15                    0             123   88  ...  35.2     0.197   29

[5 rows x 8 columns]

In [8]:
np.bincount(y)

array([377, 199])

#Feature Engineering

After train/test split perform feature engineering on training data only.

In [14]:
!pip install featuretools

     |████████████████████████████████| 296kB 5.3MB/s 
     |████████████████████████████████| 665kB 34.4MB/s 
     |████████████████████████████████| 92kB 9.4MB/s 
     |████████████████████████████████| 102kB 10.5MB/s 
  Created wheel for contextvars: filename=contextvars-2.4-cp36-none-any.whl size=7666 sha256=3fa1dc446260811476b93e8c716c589490ebef55f88a2d1bc8fa7e6ad23086b6
  Stored in directory: /root/.cache/pip/wheels/a5/7d/68/1ebae2668bda2228686e3c1cf16f2c2384cea6e9334ad5f6de
  Created wheel for locket: filename=locket-0.2.0-cp36-none-any.whl size=4040 sha256=fe236de7e9d18695204c83972f13cacaf6ef4be1deffce5c69b4fdf51152e755
  Stored in directory: /root/.cache/pip/wheels/26/1e/e8/4fa236ec931b1a0cdd61578e20d4934d7bf188858723b84698
Successfully built contextvars locket
ERROR: distributed 2.30.1 has requirement cloudpickle>=1.5.0, but you'll have cloudpickle 1.3.0 which is incompatible.
  Found existing installation: distributed 1.25.3
    Uninstalling distributed-1.25.3:
      Success

In [15]:
# Use featuretools to select best features to use
import featuretools as ft

In [17]:
# Create our first entityset
#entity_set = ft.EntitySet(id = 'clients')
diabetes_df = X_train
entities = {
    "diabetes" : (diabetes_df, "Id")
}

In [19]:
diabetes_df.head()

Id  num_times_pregnant  plasma_glucose  ...   BMI  pedigree  age
437   0                   6             102  ...  30.8     0.180   36
63    1                   7             142  ...  28.8     0.687   61
208   2                   1             119  ...  35.5     0.280   25
60    3                   8             143  ...  34.9     0.129   41
15    4                   0             123  ...  35.2     0.197   29

[5 rows x 9 columns]

In [18]:
feature_matrix_diabetes = ft.dfs(entities=entities,
                                 relationships=None,
                                 target_entity="diabetes")

/usr/local/lib/python3.6/dist-packages/featuretools/entityset/entity.py:611: UserWarning: index Id not found in dataframe, creating new integer column
  "integer column".format(index))


In [20]:
feature_matrix_diabetes

(     num_times_pregnant  plasma_glucose  DBP  ...   BMI  pedigree  age
 Id                                            ...                     
 0                     6             102   82  ...  30.8     0.180   36
 1                     7             142   60  ...  28.8     0.687   61
 2                     1             119   44  ...  35.5     0.280   25
 3                     8             143   66  ...  34.9     0.129   41
 4                     0             123   88  ...  35.2     0.197   29
 ..                  ...             ...  ...  ...   ...       ...  ...
 455                   3              87   60  ...  21.8     0.444   21
 456                   7             100    0  ...  30.0     0.484   32
 457                   0             126   86  ...  27.4     0.515   21
 458                   4             103   60  ...  24.0     0.966   33
 459                   3             129   92  ...  36.4     0.968   32
 
 [460 rows x 8 columns],
 [<Feature: num_times_pregnant>,
  <F

# Build Model

In [9]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(max_depth=2)
clf.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=2, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

# Estimate Model Performance

In [10]:
from sklearn.metrics import confusion_matrix

pred_val = clf.predict(X_val)
pred_val

confusion_matrix(y_val, pred_val)

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

array([[78,  3],
       [19, 16]])

In [11]:
from sklearn.metrics import classification_report

print(classification_report(y_val, pred_val))

              precision    recall  f1-score   support

           0       0.80      0.96      0.88        81
           1       0.84      0.46      0.59        35

    accuracy                           0.81       116
   macro avg       0.82      0.71      0.73       116
weighted avg       0.82      0.81      0.79       116



# Create Submission File on Test Data

In [12]:
test_df = pd.read_csv('diabetes_test.csv')

# Make sure to transform/create the features the same way you did for training
# For now, nothing to do

X_test = test_df.drop([Id_col], axis=1)

# Use your model to make predictions
pred_test = clf.predict(X_test)

# We will look at the predicted prices to ensure we have something sensible.
print(pred_test)

my_submission = pd.DataFrame({'Id': test_df.Id, 'Predicted': pred_test})

my_submission.head()

# you could use any filename. We choose submission here
my_submission.to_csv('my_submission.csv', index=False)

[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 1
 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0
 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0]


Id  Predicted
0  669          0
1  325          0
2  625          0
3  691          0
4  474          0